
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE BEGINTEAM CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT GARBAGE IMG OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLEstart : tablename : CONTENT\n            | CONTENT nameskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | OPENSPAN skiptag\n               | CLOSESPAN skiptag\n               | OPENHEADER skiptag\n               | CLOSEHEADER skiptag\n               | IMG skiptag\n               | handleData : OPENDATA skiptag CLOSEDATA handleData\n                  | OPENDATA OPENSPAN OPENSPAN CONTENT CLOSESPAN OPENHREF CONTENT CLOSEHREF CLOSESPAN CLOSEDATA handleData\n                  | handlerow : OPENROW OPENHEADER CONTENT skiptag CLOSEROW handlerow\n                 | OPENROW handleData CLOSEROW handlerow  \n                 |table : BEGINTEAM  OPENTABLE  handlerowempty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTEAM':([0,],[3,]),'$end':([1,2,4,5,11,23,34,37,],[0,-1,-18,-19,-18,-17,-18,-16,]),'OPENTABLE':([3,],[4,]),'OPENROW':([4,11,34,],[6,6,6,]),'OPENHEADER':([6,9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[7,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,]),'OPENDATA':([6,24,43,],[9,9,9,]),'CLOSEROW':([6,8,10,14,15,16,17,18,19,20,21,22,24,26,27,28,29,30,31,32,33,35,43,44,],[-15,11,-12,-12,-12,-12,-12,-12,-12,-12,34,-12,-15,-7,-4,-8,-5,-6,-9,-10,-11,-13,-15,-14,]),'CONTENT':([7,9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[10,14,14,14,14,14,14,14,14,14,14,14,36,14,14,40,14,14,14,]),'OPENSPAN':([9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[13,22,25,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,]),'OPENHREF':([9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[16,16,16,16,16,16,16,16,16,16,16,16,16,39,16,16,16,16,]),'CLOSEHREF':([9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,41,17,17,]),'CLOSESPAN':([9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[15,15,15,15,15,15,15,15,15,15,15,15,38,15,15,15,42,15,]),'CLOSEHEADER':([9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,]),'IMG':([9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,]),'CLOSEDATA':([9,12,13,14,15,16,17,18,19,20,22,25,26,27,28,29,30,31,32,33,36,38,39,40,41,42,],[-12,24,-12,-12,-12,-12,-12,-12,-12,-12,-12,-12,-7,-4,-8,-5,-6,-9,-10,-11,-12,-12,-12,-12,-12,43,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'handlerow':([4,11,34,],[5,23,37,]),'handleData':([6,24,43,],[8,35,44,]),'skiptag':([9,10,13,14,15,16,17,18,19,20,22,25,36,38,39,40,41,42,],[12,21,26,27,28,29,30,31,32,33,26,26,27,28,29,27,30,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','p2.py',111),
  ('name -> CONTENT','name',1,'p_name','p2.py',117),
  ('name -> CONTENT name','name',2,'p_name','p2.py',118),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','p2.py',127),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','p2.py',128),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','p2.py',129),
  ('skiptag -> OPENSPAN skiptag','skiptag',2,'p_skiptag','p2.py',130),
  ('skiptag -> CLOSESPAN skiptag','skiptag',2,'p_skiptag','p2.py',131),
  ('skiptag -> OPENHEADER skiptag','skiptag',2,'p_skiptag','p2.py',132),
  ('skiptag -> CLOSEHEADER skiptag','skiptag',2,'p_skiptag','p2.py',133),
  ('skiptag -> IMG skiptag','skiptag',2,'p_skiptag','p2.py',134),
  ('skiptag -> <empty>','skiptag',0,'p_skiptag','p2.py',135),
  ('handleData -> OPENDATA skiptag CLOSEDATA handleData','handleData',4,'p_handleData','p2.py',138),
  ('handleData -> OPENDATA OPENSPAN OPENSPAN CONTENT CLOSESPAN OPENHREF CONTENT CLOSEHREF CLOSESPAN CLOSEDATA handleData','handleData',11,'p_handleData','p2.py',139),
  ('handleData -> <empty>','handleData',0,'p_handleData','p2.py',140),
  ('handlerow -> OPENROW OPENHEADER CONTENT skiptag CLOSEROW handlerow','handlerow',6,'p_handlerow','p2.py',148),
  ('handlerow -> OPENROW handleData CLOSEROW handlerow','handlerow',4,'p_handlerow','p2.py',149),
  ('handlerow -> <empty>','handlerow',0,'p_handlerow','p2.py',150),
  ('table -> BEGINTEAM OPENTABLE handlerow','table',3,'p_table','p2.py',154),
  ('empty -> <empty>','empty',0,'p_empty','p2.py',159),
  ('content -> CONTENT','content',1,'p_content','p2.py',163),
  ('content -> empty','content',1,'p_content','p2.py',164),
]
